name = "Quilt Tech"
author = "Marios M"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44122a77d2299686a089710a4826fb6c886f02f6511dd29bab39a22fb25b5e7e"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
